<a href="https://colab.research.google.com/github/isaiastrajano/BootCamp_Python_DataScience/blob/main/Exercicios_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercícios da biblioteca Numpy de Python


# Exercício 1

Exercícios 1

Inspecionando um Array NumPy

Um objeto numpy possui atributos e métodos, herdados da classe (numpy.ndarray). Crie um array  e inspecione os seguintes atributos:

shape: uma tupla que contém o número de elementos (tamanho) em cada dimensão do array;

size: número total de elementos do array;

ndim: número de dimensões (eixos);

nbytes: número de bytes utilizado no armazenamento dos dados;

dtype: data type dos elementos do array.

In [ ]:
import numpy as np

In [ ]:
array = np.array([1, 2, 3, 4])
array

array([1, 2, 3, 4])

In [ ]:
print("O shape do array: ", array.shape)

O shape do array:  (4,)


In [ ]:
array.size

4

In [ ]:
array.ndim

1

In [ ]:
array.dtype

dtype('int64')

# Exercício 2

Exercício 2

Com base no exercício anterior crie uma função que receba um array e mostre na tela seus atributos. Verifique se o argumento inserido é de fato um objeto numpy. Use também a função built-in type() para verificar a classe do objeto.

In [ ]:
def funcao (array):
    if isinstance(array, np.ndarray):
       print("O shape : ", array.shape)
       print("O tamanho : ", array.size)
       print("Dimensões : ", array.ndim)
       print("Dtipo de arquivo : ", array.dtype)
       print("O tipo do arquivo : ", type(array))
       print(array)
    else:
       return 'valor não é tipo np.array'

In [ ]:
print(funcao(array))

O shape :  (4,)
O tamanho :  4
Dimensões :  1
Dtipo de arquivo :  int64
O tipo do arquivo :  <class 'numpy.ndarray'>
[1 2 3 4]
None


In [ ]:
print(funcao(5))

valor não é tipo np.array


# Exercício 3

Exercício 3

Use a função np.array() para criar os arrays unidimensionais listados abaixo:

a) Use uma lista como argumento e obtenha:

array([-1,  4,  7,  9])

b) Use a função range() e obtenha:
      
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

c)Use uma tupla como argumento e obtenha:
    
array([10, 11, 12, 13, 14])

d) Use a função range() e obtenha:

array([1990, 1995, 2000, 2005, 2010, 2015, 2020])

e) Use a função range() e obtenha:

In [ ]:
#a
array = np.array([-1, 4, 7, 9])

In [ ]:
#b
array1 = np.array(range(1, 11))

In [ ]:
#c
val = (10, 11, 12, 23, 14)
array2 = np.array(val)
array2

array([10, 11, 12, 23, 14])

In [ ]:
#d
array3 = np.array(range(1990, 2025, 5))
array3

array([1990, 1995, 2000, 2005, 2010, 2015, 2020])

In [ ]:
#e
array4 = np.array(range(2020, 1890, -10))
array4

array([2020, 2010, 2000, 1990, 1980, 1970, 1960, 1950, 1940, 1930, 1920,
       1910, 1900])

# Exercício 4

Exercício 4

A função np.ones() permite criar um array preenchido com o número 1 em todas as suas entradas. Podemos especificar como argumentos o shape e o tipo de dado dtype do array. Use esta função para criar os arrays a seguir:

a)
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


b)
array([[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]])

c)
array([[1, 1],
           [1, 1],
           [1, 1]])

In [ ]:

#a
array5 = np.ones(3)
array6 = np.ones(shape = (4, 4))

In [ ]:
array5

array([1., 1., 1.])

In [ ]:
array6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:

#b
array7 = np.ones((3, 2), dtype=float)
array7

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# Exercício 5


Exercício 5

A função np.zeros() permite criar um array preenchido com o número 0 em todas as suas entradas. Podemos especificar como argumentos o shape e o tipo de dado dtype do array (default é o float). Use esta função para criar os arrays a seguir:

a)
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

b)
array([[0., 0.],
      [0., 0.]])  

c)
array([[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.]])

In [ ]:
#a
array8 = np.zeros(10)
array8

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#b
array9 = np.zeros(shape = (2, 2))
array9

array([[0., 0.],
       [0., 0.]])

In [ ]:
#c
array10 = np.zeros(shape = (4, 6))
array10

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# Exercício 6

Exercício 6

Crie os arrays a seguir:

   

a)
array([[10],
           [15],
           [20],
           [25],
           [30],
           [35],
           [40],
           [45]])

b)
array([-50, -45, -40, -35, -30, -25, -20, -15, -10,  -5])


c)
array([[ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
      [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
      [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
      [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
      [130, 132, 134, 136, 138, 140, 142, 144, 146, 148]])

Dica: use np.arange() ou np.array(range()).

In [ ]:

#a
array11 = np.arange(10, 46, 5)
array11 = np.split(array11, len(array11))
array11

#ou

#a = np.arange(10, 50, 5).reshape(-1, 1)

[array([10]),
 array([15]),
 array([20]),
 array([25]),
 array([30]),
 array([35]),
 array([40]),
 array([45])]

In [ ]:
#b
array12 = np.arange(-50, -4, 5)
array12

array([-50, -45, -40, -35, -30, -25, -20, -15, -10,  -5])

In [ ]:
#c

array13 = np.array(range(50, 149, 2)).reshape(5, 10)
array13
#np.array(range(12)).reshape(3,4)

array([[ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
       [130, 132, 134, 136, 138, 140, 142, 144, 146, 148]])

# Exercício 7

Exercício 7

Utilize a função np.full(shape, fill_value, dtype) para criar os arrays a seguir. Esta função permite criar um array com um shape e dtype definidos pelo usuário, preenchido com um determinado valor.

a)
array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

b)
array([[-5., -5., -5., -5.],
           [-5., -5., -5., -5.],
           [-5., -5., -5., -5.],
           [-5., -5., -5., -5.]])


c)
array([[3, 3, 3],
      [3, 3, 3],
      [3, 3, 3]])

d)
array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])

In [ ]:

#a
array14 = np.full(shape = (10), fill_value = 5, dtype = float)
array14

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
#b
array15 = np.full(shape = (4, 4), fill_value = -5, dtype = float)
array15

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [ ]:
array16 = np.full((3, 3), 3, int)
array16

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [ ]:
array17 = np.full((10, 10), 50, int)
array17

array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])

# Exercício 8

Exercício 8

Defina o array K e verifique se há dados ausentes (missing data). Use a função np.isnan().

array([[ nan,   1.,  10.,   0.],
      [ nan,  nan,  nan,  nan],
      [100.,  50.,  nan, -25.],
      [ 30.,  nan,  nan, 130.]])

In [ ]:
k = np.array =([[np.nan, 1., 10., 0.], [np.nan, np.nan, np.nan, np.nan], [100, 50, np.nan, -25], [30, np.nan, np.nan, 130]])
y = np.isnan(k)
y

array([[ True, False, False, False],
       [ True,  True,  True,  True],
       [False, False,  True, False],
       [False,  True,  True, False]])

In [ ]:
print(f'O somatório de valores nulos é: {y.sum()}')

O somatório de valores nulos é: 8


# Exercício 9

Exercício 9

A função np.linspace() retorna um array com números contendo espaçamento uniforme em um intervalo definido. Crie um array com números dentro do intervalo [1,21] em 5 partes.

Retorno esperado:
array([ 1.,  6., 11., 16., 21.])

In [ ]:
array18 = np.linspace(1, 2, 5)
array18
#np.linspace(início, fim , partes(qtd de elementos)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

# Exercício 10

Exercício 10

A função np.logspace() retorna números com espaçamento uniforme em uma escala logarítmica. Crie um array com números dentro do intervalo [1, 51] em 10 partes com a função np.logspace().

Retorno esperado:

array([[1.00000000e+01],
      [3.59381366e+06],
      [1.29154967e+12],
      [4.64158883e+17],
      [1.66810054e+23],
      [5.99484250e+28],
      [2.15443469e+34],
      [7.74263683e+39],
      [2.78255940e+45],
      [1.00000000e+51]])

In [ ]:
array19 = np.logspace(1, 51, 10).reshape(-1,1)
array19

array([[1.00000000e+01],
       [3.59381366e+06],
       [1.29154967e+12],
       [4.64158883e+17],
       [1.66810054e+23],
       [5.99484250e+28],
       [2.15443469e+34],
       [7.74263683e+39],
       [2.78255940e+45],
       [1.00000000e+51]])

# Exercício 11

Exercício 11