<a href="https://colab.research.google.com/github/isaiastrajano/BootCamp_Python_DataScience/blob/main/Exercicio_numpy_algebralinear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Exercício 1

Exercício 1

In [2]:
a = [1, 2, 3, 2, 1, -1]

# Exercício 2

Exercício 2

In [3]:
#a
li = [0, 1, 2, 3, 4, 5, 6]
e = np.array(li).reshape(7, 1)
e

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [4]:
#b
lf = [1, 0, 3, -10]
f = np.array(lf)
f

array([  1,   0,   3, -10])

In [5]:
#c
lg = [1, 2, 3, 4, 5]
g = np.array(lg)
g

array([1, 2, 3, 4, 5])

# Exercício 3

Exercício 3

In [14]:
#a
la = [0, 0, 0, 0]
a = np.array(la, dtype = int).reshape(2, 2)
a

array([[0, 0],
       [0, 0]])

In [8]:
#b
b = np.zeros(shape = (3, 5), dtype = int)
b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [9]:
#c
c = np.ones(shape = (5, 5), dtype = int)
c

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
#d
d = np.eye(2, dtype=int)
d

array([[1, 0],
       [0, 1]])

In [11]:
#e
e = np.eye(3, k = 0, dtype = int)
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [12]:
#f
f = np.eye(6, k = 0, dtype = int)
f

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

# Exercício 4

Exercício 4

In [116]:
#a
t = np.triu([[1,2,3],[4,5,6],[7,8,9]])
t
#função triu põe o zero abaixo

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [118]:
#b
t2 = np.tril([[1,2,3],[4,5,6],[7,8,9]])
t2
#função tril põe o zero acima

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [119]:
#c
t3d = np.arange(100, 125)
t3 = np.triu(t3d.reshape(5, 5))
t3

array([[100, 101, 102, 103, 104],
       [  0, 106, 107, 108, 109],
       [  0,   0, 112, 113, 114],
       [  0,   0,   0, 118, 119],
       [  0,   0,   0,   0, 124]])

# Exercício 5

de acordo com a documentação

np.diag(x)

array([0, 4, 8])

np.diag(x, k=1)

array([1, 5])

np.diag(x, k=-1)

array([3, 7])

o comando n.diag(np.diag(x)) vai retornar a matriz com a matrix x em evidência

Exercício 5

In [141]:
#a
x = [[7, 2, 3], [4, 1, 6], [7, 8, -1]]
t5 = np.diag(np.diag(x))
t5

array([[ 7,  0,  0],
       [ 0,  1,  0],
       [ 0,  0, -1]])

In [145]:
#b
t6 = np.full(16, 3).reshape(4, 4)
t6 = np.diag(np.diag(t6))
t6

array([[3, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 3]])

In [151]:
#c
t7 = np.arange(-5, 0)
t7 = np.triu(t7)
t7 = np.diag(np.diag(t7))
t7

array([[-5,  0,  0,  0,  0],
       [ 0, -4,  0,  0,  0],
       [ 0,  0, -3,  0,  0],
       [ 0,  0,  0, -2,  0],
       [ 0,  0,  0,  0, -1]])

A resposta do exercício me lembrou que a função np.diag() vai trazer a o valor da diagonal numa matriz e preencher com 0 os valores restantes

A = np.diag([7,1,-1])
B = np.diag([3]*4)
C = np.diag(range(-5,0))